AllCops:
  NewCops: enable

require:
  - rubocop-performance

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  EnforcedStyle: empty_lines
